### ISSUE TITLE
Copy btn to clipboard is not working properly (its copying wrong btn)

### ISSUE THREAD

**Issue by khazifire** [khazifire/DripUI#3]
the problem is probably with the Id passed down to the copy to clipboard function

**Comment by sainathd07** [comment]
is the issue with all buttons or only with certain buttons..can you specify

**Comment by khazifire** [comment]
the function works fine, but the id passed to the function is the problem a wrong text is copied to the clipboard

**Comment by Michelle031** [comment]
Okay
Please can I be assigned this issue

**Comment by khazifire** [comment]
@Michelle031 have a look at that page, and try copying some of the buttons (then see if its copying the correct button)

![image](https://user-images.githubusercontent.com/73513866/193437108-5069e5d8-bb37-484f-90b1-bfc4a4db842c.png)

**Comment by Jaivrat12** [comment]
Hey there! I think I can help with this issue!!
Can you please assign it to me?

**Comment by khazifire** [comment]
@Jaivrat12 i assigned it to you, you can have a check

**Comment by Jaivrat12** [comment]
Hey @khazifire! I fixed the bug and I think that the `btnAreaRef` in [pages/docs/buttons.js](https://github.com/khazifire/DripUI/blob/main/pages/docs/buttons.js#L10) file isn't needed anymore. Can I remove it from the code and then make a PR? Or should I ignore that as you may need it in the future?

BTW the `btnAreaRef` can only be used on one element at a time that's why it won't work for multiple elements, you need to have an array of `btnAreaRef`s to do that. So, I think removing it is better.

**Comment by khazifire** [comment]
@Jaivrat12 You can simply comment it out 😌🙂
